// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import javax.ejb.AfterCompletion;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.chrome.ChromeOptions;

public class RegisterLogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/usr/lib/chromium-browser/chromedriver");
    
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    if (driver != null) {
        driver.quit();
    }
  }
  @Test
  public void registerlogout() {
    // Generate a random username and email using UUID
    String randomPart = UUID.randomUUID().toString().substring(0, 8);
    String username = "username" + randomPart;
    String email = "username" + randomPart + "@gmail.com";
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(1848, 1053));
    driver.findElement(By.linkText("Register now")).click();
    driver.findElement(By.cssSelector(".input-field:nth-child(1) > label")).click();
    driver.findElement(By.id("username")).sendKeys(username);
    driver.findElement(By.id("email")).sendKeys(email);
    driver.findElement(By.id("password")).sendKeys("123");
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("confirmPassword")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
}